f_number=input("enter first number")
s_number=input("enter second number")
sum_num=int(f_number) + int(s_number)
print(sum_num)
diff_num=int(f_number) - int(s_number)
print(diff_num)
quot_num=int(f_number) / int(s_number)
print(quot_num)
pro_num=int(f_number) * int(s_number)
print(pro_num)